swagger: "2.0"
info:
  title: title
  description: API description in Markdown.
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes:
  - https
paths:
  /pathName:
    get:
      summary: summary
      description: Optional extended description in Markdown.
      produces:
        - application/json
      responses:
        200:
          description: OK