swagger: "2.0"
info:
  title: simple cab api
  description: API to return number of trips a medallion has made
  version: 1.0.0
host: localhost:8000
basePath: /api
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /medallion:
    get:
      summary: Get the total trips a medallion/s has made
      parameters:
      - in: query
        name: medallion
      - in: query
          name: ignoreCache
          type: boolean
          description: Flag to use the cache or not
      responses:
        200:
          description: An object containing medallion trip pairs
          type: array
          items:
            type: object
              properties:
                medallion:
                  type: string
                trips:
                  type: integer
        400:
          description: Bad Request
  /medallion/{medallionId}:
    get:
      summary: Get the number of trips a medallion has made on a certain date
      parameters:
        - in: path
          name: medallion
          required: true
          type: string
          description: The cab medallion id
        - in: query
          name: date
          type: string
          required: true
          description: Date to filter the number of trips a medallion made on a specific day
        - in: query
          name: ignoreCache
          type: boolean
          description: Flag to use the cache or not
      responses:
        200:
          description: Object containing the number of trips a medallion has made given a date
          type: object
            properties:
              medallion:
                type: string
              trips:
        400:
          description: Bad Request
  /medallion/clearCache:
    get:
      summary: Clear the medallion cache
    responses:
      204:
        description: No Content

  